-- 0000_init.sql — clinic-translator initial schema
-- Generated by hand to match lib/db/schema.ts; equivalent to drizzle-kit generate output.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ----- Enums -----
DO $$ BEGIN
  CREATE TYPE "source" AS ENUM ('desktop');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE "urgency" AS ENUM ('low', 'normal', 'high', 'urgent');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE "outcome" AS ENUM ('completed', 'transferred', 'voicemail', 'dropped', 'fallback');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE "utterance_role" AS ENUM ('patient', 'staff');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE "lang" AS ENUM ('es', 'en');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE "staff_role" AS ENUM ('owner', 'staff', 'admin');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE "glossary_category" AS ENUM ('medication', 'symptom', 'procedure', 'billing', 'scheduling', 'general');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE "audit_action" AS ENUM ('view', 'edit', 'create', 'delete', 'auth_login', 'auth_logout', 'translate_refused', 'decrypt_failed');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE "audit_target_type" AS ENUM ('patient', 'call', 'utterance', 'staff_user', 'glossary_term');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- ----- Tables -----
CREATE TABLE IF NOT EXISTS "patients" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "callback_phone_enc" bytea,
  "name_enc" bytea,
  "dob_last4_enc" bytea,
  "preferred_dialect" text,
  "notes_enc" bytea,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "last_seen_at" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "staff_users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "email" text NOT NULL,
  "name" text,
  "role" "staff_role" NOT NULL DEFAULT 'staff',
  "last_login_at" timestamp with time zone,
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "staff_users_email_uq" ON "staff_users" ("email");

CREATE TABLE IF NOT EXISTS "calls" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "patient_id" uuid REFERENCES "patients"("id") ON DELETE CASCADE,
  "source" "source" NOT NULL DEFAULT 'desktop',
  "started_at" timestamp with time zone NOT NULL DEFAULT now(),
  "ended_at" timestamp with time zone,
  "urgency" "urgency" NOT NULL DEFAULT 'normal',
  "outcome" "outcome",
  "staff_user_id" uuid REFERENCES "staff_users"("id") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "calls_started_at_idx" ON "calls" ("started_at");
CREATE INDEX IF NOT EXISTS "calls_patient_id_idx" ON "calls" ("patient_id");

CREATE TABLE IF NOT EXISTS "utterances" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "call_id" uuid NOT NULL REFERENCES "calls"("id") ON DELETE CASCADE,
  "role" "utterance_role" NOT NULL,
  "lang" "lang" NOT NULL,
  "text_enc" bytea,
  "translation_enc" bytea,
  "ts" timestamp with time zone NOT NULL DEFAULT now(),
  "audio_storage_key" text
);
CREATE INDEX IF NOT EXISTS "utterances_call_id_idx" ON "utterances" ("call_id");
CREATE INDEX IF NOT EXISTS "utterances_ts_idx" ON "utterances" ("ts");

CREATE TABLE IF NOT EXISTS "glossary_terms" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "en" text NOT NULL,
  "es" text NOT NULL,
  "dialect" text,
  "category" "glossary_category" NOT NULL DEFAULT 'general',
  "created_by" uuid REFERENCES "staff_users"("id") ON DELETE SET NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "audit_log" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "actor_id" uuid REFERENCES "staff_users"("id") ON DELETE SET NULL,
  "action" "audit_action" NOT NULL,
  "target_type" "audit_target_type" NOT NULL,
  "target_id" uuid,
  "ts" timestamp with time zone NOT NULL DEFAULT now(),
  "ip_addr" text,
  "reason" text
);
CREATE INDEX IF NOT EXISTS "audit_log_ts_idx" ON "audit_log" ("ts");
CREATE INDEX IF NOT EXISTS "audit_log_actor_idx" ON "audit_log" ("actor_id");
CREATE INDEX IF NOT EXISTS "audit_log_target_idx" ON "audit_log" ("target_type", "target_id");

-- ----- audit_log immutability (spec §8) -----
REVOKE UPDATE, DELETE ON "audit_log" FROM PUBLIC;

CREATE OR REPLACE FUNCTION audit_log_no_modify() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'audit_log is append-only; UPDATE/DELETE forbidden';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS audit_log_no_modify_trg ON "audit_log";
CREATE TRIGGER audit_log_no_modify_trg
  BEFORE UPDATE OR DELETE ON "audit_log"
  FOR EACH ROW EXECUTE FUNCTION audit_log_no_modify();
